#!/usr/bin/env python
# -*- coding: UTF8 -*-
#
# generated by wxGlade HG on Sat May 24 09:44:53 2014
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

from wxPython.wx import *
import gettext
from MyDialog import MyDialog

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wxPySimpleApp(0)
    wxInitAllImageHandlers()
    dialog_metadata = MyDialog(None, wxID_ANY, "")
    app.SetTopWindow(dialog_metadata)
    dialog_metadata.Show()
    app.MainLoop()