// -*- C++ -*-
//
// generated by wxGlade HG on Sat May 24 09:37:54 2014
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "MyDialog.h"

// begin wxGlade: ::extracode
// end wxGlade


MyDialog::MyDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: MyDialog::MyDialog
    sizer_3_staticbox = new wxStaticBox(this, wxID_ANY, _("Herds"));
    sizer_7_staticbox = new wxStaticBox(this, wxID_ANY, _("Maintainer"));
    sizer_11_staticbox = new wxStaticBox(this, wxID_ANY, _("Long Description"));
    label_1 = new wxStaticText(this, wxID_ANY, _("Enter name of herd:"));
    text_ctrl_herd = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    button_herd = new wxButton(this, wxID_ANY, _("Add"));
    const wxString *list_box_herds_choices = NULL;
    list_box_herds = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, list_box_herds_choices, 0);
    button_remove_herd = new wxButton(this, wxID_ANY, _("Remove herd"));
    text_ctrl_long_desc = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    label_email = new wxStaticText(this, wxID_ANY, _("Email address of maintainer"));
    text_ctrl_email = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_name = new wxStaticText(this, wxID_ANY, _("Full name of maintainer (optional)"));
    text_ctrl_name = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_desc = new wxStaticText(this, wxID_ANY, _("Description of maintainership"));
    text_ctrl_desc = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    button_remove_maintainer = new wxButton(this, wxID_ANY, _("Clear All"));
    button_add_maintainer = new wxButton(this, wxID_ANY, _("Add"));
    tree_ctrl_1 = new wxTreeCtrl(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT|wxTR_DEFAULT_STYLE|wxSUNKEN_BORDER);
    stc = new GentooSTC(this, wxID_ANY);
    button_save = new wxButton(this, wxID_OK, _("Save"));
    button_cancel = new wxButton(this, wxID_CANCEL, _("Cancel"));
    button_preview = new wxButton(this, wxID_ANY, _("Preview"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MyDialog::set_properties()
{
    // begin wxGlade: MyDialog::set_properties
    SetTitle(_("metadata.xml"));
    // end wxGlade
}


void MyDialog::do_layout()
{
    // begin wxGlade: MyDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxVERTICAL);
    sizer_7_staticbox->Lower();
    wxStaticBoxSizer* sizer_7 = new wxStaticBoxSizer(sizer_7_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxHORIZONTAL);
    sizer_3_staticbox->Lower();
    wxStaticBoxSizer* sizer_3 = new wxStaticBoxSizer(sizer_3_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_10 = new wxBoxSizer(wxHORIZONTAL);
    sizer_11_staticbox->Lower();
    wxStaticBoxSizer* sizer_11 = new wxStaticBoxSizer(sizer_11_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    sizer_4->Add(label_1, 0, wxTOP, 12);
    sizer_5->Add(text_ctrl_herd, 1, 0, 0);
    sizer_5->Add(button_herd, 0, 0, 0);
    sizer_4->Add(sizer_5, 0, wxALL|wxEXPAND, 6);
    sizer_3->Add(sizer_4, 0, wxEXPAND, 0);
    sizer_3->Add(list_box_herds, 1, wxALL|wxEXPAND, 6);
    sizer_3->Add(button_remove_herd, 0, wxALL, 12);
    sizer_11->Add(text_ctrl_long_desc, 1, wxALL|wxEXPAND, 6);
    sizer_10->Add(sizer_11, 1, wxEXPAND, 0);
    sizer_3->Add(sizer_10, 0, wxEXPAND, 0);
    sizer_2->Add(sizer_3, 1, wxEXPAND, 0);
    sizer_7->Add(label_email, 0, wxTOP, 12);
    sizer_7->Add(text_ctrl_email, 0, wxALL|wxEXPAND, 4);
    sizer_7->Add(label_name, 0, wxTOP, 4);
    sizer_7->Add(text_ctrl_name, 0, wxALL|wxEXPAND, 6);
    sizer_7->Add(label_desc, 0, wxTOP, 4);
    sizer_7->Add(text_ctrl_desc, 0, wxALL|wxEXPAND, 6);
    sizer_8->Add(button_remove_maintainer, 0, wxALL, 8);
    sizer_8->Add(button_add_maintainer, 0, wxALL, 8);
    sizer_7->Add(sizer_8, 0, wxEXPAND, 0);
    sizer_6->Add(sizer_7, 1, wxEXPAND, 0);
    sizer_6->Add(tree_ctrl_1, 1, wxEXPAND, 0);
    sizer_2->Add(sizer_6, 1, wxEXPAND, 0);
    sizer_2->Add(stc, 2, wxALL|wxEXPAND, 6);
    sizer_1->Add(sizer_2, 0, wxEXPAND, 0);
    sizer_9->Add(button_save, 0, wxALL, 20);
    sizer_9->Add(button_cancel, 0, wxALL, 20);
    sizer_9->Add(button_preview, 0, wxALL, 20);
    sizer_1->Add(sizer_9, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

