// -*- C++ -*-
//
// generated by wxGlade HG on Sat May 24 13:44:22 2014
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef METADATAXMLDIALOG_H
#define METADATAXMLDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>
#include "wx/intl.h"

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MyDialog: public wxDialog {
public:
    // begin wxGlade: MyDialog::ids
    // end wxGlade

    MyDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: MyDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyDialog::attributes
    wxStaticBox* sizer_7_staticbox;
    wxStaticBox* sizer_3_staticbox;
    wxStaticBox* sizer_11_staticbox;
    wxStaticText* label_1;
    wxTextCtrl* text_ctrl_herd;
    wxButton* button_herd;
    wxListBox* list_box_herds;
    wxButton* button_remove_herd;
    wxTextCtrl* text_ctrl_long_desc;
    wxStaticText* label_email;
    wxTextCtrl* text_ctrl_email;
    wxStaticText* label_name;
    wxTextCtrl* text_ctrl_name;
    wxStaticText* label_desc;
    wxTextCtrl* text_ctrl_desc;
    wxButton* button_remove_maintainer;
    wxButton* button_add_maintainer;
    wxTreeCtrl* tree_ctrl_1;
    GentooSTC* stc;
    wxButton* button_save;
    wxButton* button_cancel;
    wxButton* button_preview;
    // end wxGlade
}; // wxGlade: end class


#endif // METADATAXMLDIALOG_H
