// -*- C++ -*-
//
// generated by wxGlade HG on Sat May 24 09:06:48 2014
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef GETURIDIALOG_H
#define GETURIDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>
#include "wx/intl.h"

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class GetURIDialog: public wxDialog {
public:
    // begin wxGlade: GetURIDialog::ids
    // end wxGlade

    GetURIDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: GetURIDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: GetURIDialog::attributes
    wxStaticText* label_uri;
    wxTextCtrl* URI;
    wxStaticText* label_template;
    wxComboBox* combo_box_1;
    wxStaticLine* static_line_2;
    wxButton* button_cancel;
    wxButton* button_ok;
    // end wxGlade
}; // wxGlade: end class


#endif // GETURIDIALOG_H
