// -*- C++ -*-
//
// generated by wxGlade HG on Sat May 24 09:06:48 2014
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "GetURIDialog.h"

// begin wxGlade: ::extracode
// end wxGlade



GetURIDialog::GetURIDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: GetURIDialog::GetURIDialog
    label_uri = new wxStaticText(this, wxID_ANY, _("Package URI:"));
    URI = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_template = new wxStaticText(this, wxID_ANY, _("Template:"));
    const wxString *combo_box_1_choices = NULL;
    combo_box_1 = new wxComboBox(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, combo_box_1_choices, wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    static_line_2 = new wxStaticLine(this, wxID_ANY);
    button_cancel = new wxButton(this, wx.ID_CANCEL, _("Cancel"));
    button_ok = new wxButton(this, wx.ID_OK, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void GetURIDialog::set_properties()
{
    // begin wxGlade: GetURIDialog::set_properties
    SetTitle(_("Enter URI for package"));
    SetSize(wxSize(407, 146));
    URI->SetMinSize(wxSize(304, 22));
    button_ok->SetDefault();
    // end wxGlade
}


void GetURIDialog::do_layout()
{
    // begin wxGlade: GetURIDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(label_uri, 0, wxLEFT, 4);
    sizer_2->Add(URI, 1, wxLEFT, 12);
    sizer_1->Add(sizer_2, 0, wxTOP|wxBOTTOM|wxEXPAND, 10);
    sizer_3->Add(label_template, 0, wxLEFT|wxALIGN_RIGHT, 4);
    sizer_3->Add(combo_box_1, 1, wxLEFT, 20);
    sizer_1->Add(sizer_3, 0, wxTOP|wxBOTTOM|wxEXPAND, 10);
    sizer_1->Add(static_line_2, 0, wxEXPAND, 0);
    sizer_4->Add(button_cancel, 0, 0, 0);
    sizer_4->Add(20, 20, 0, 0, 0);
    sizer_4->Add(button_ok, 0, 0, 0);
    sizer_1->Add(sizer_4, 0, wxALL|wxEXPAND, 12);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}


class MyApp: public wxApp {
public:
    bool OnInit();
protected:
    wxLocale m_locale;  // locale we'll be using
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    m_locale.Init();
#ifdef APP_LOCALE_DIR
    m_locale.AddCatalogLookupPathPrefix(wxT(APP_LOCALE_DIR));
#endif
    m_locale.AddCatalog(wxT(APP_CATALOG));

    wxInitAllImageHandlers();
    GetURIDialog* dialog_1 = new GetURIDialog(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(dialog_1);
    dialog_1->Show();
    return true;
}