#!/usr/bin/env python
# -*- coding: ANSI_X3.4-1968 -*-
#
# generated by wxGlade HG on Sat May 24 09:30:08 2014
#

from wxPython.wx import *

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MetadataDialog(wxDialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MetadataDialog.__init__
        kwds["style"] = wxDEFAULT_DIALOG_STYLE
        wxDialog.__init__(self, *args, **kwds)
        self.notebook_1 = wxNotebook(self, wxID_ANY)
        self.notebook_1_pane_1 = wxPanel(self.notebook_1, wxID_ANY)
        self.metadata_out = wxStyledTextCtrl(self.notebook_1_pane_1, wxID_ANY)
        self.notebook_1_pane_2 = wxPanel(self.notebook_1, wxID_ANY)
        self.sample = wxStyledTextCtrl(self.notebook_1_pane_2, wxID_ANY)
        self.button_save = wxButton(self, wxID_OK, _("Save"))
        self.button_cancel = wxButton(self, wxID_CANCEL, _("Cancel"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MetadataDialog.__set_properties
        self.SetTitle(_("metadata.xml"))
        self.SetSize((400, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MetadataDialog.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        sizer_4 = wxBoxSizer(wxHORIZONTAL)
        sizer_4.Add(self.metadata_out, 1, wxEXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_4)
        sizer_3.Add(self.sample, 1, wxEXPAND, 0)
        self.notebook_1_pane_2.SetSizer(sizer_3)
        self.notebook_1.AddPage(self.notebook_1_pane_1, _("metadata.xml"))
        self.notebook_1.AddPage(self.notebook_1_pane_2, _("sample"))
        sizer_1.Add(self.notebook_1, 1, wxALL | wxEXPAND, 8)
        sizer_2.Add(self.button_save, 0, wxLEFT, 80)
        sizer_2.Add(self.button_cancel, 0, wxLEFT, 60)
        sizer_1.Add(sizer_2, 0, wxALL | wxEXPAND, 8)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MetadataDialog
class MyApp(wxApp):
    def OnInit(self):
        wxInitAllImageHandlers()
        dialog_1 = MetadataDialog(None, wxID_ANY, "")
        self.SetTopWindow(dialog_1)
        dialog_1.Show()
        return 1

<1400938342285139005wxGlade event_handlers MyApp># end of class MyApp

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()