// -*- C++ -*-
//
// generated by wxGlade HG on Sat May 24 09:31:19 2014
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef METADATADIALOG_H
#define METADATADIALOG_H

#include <wx/wx.h>
#include <wx/image.h>
#include "wx/intl.h"

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MetadataDialog: public wxDialog {
public:
    // begin wxGlade: MetadataDialog::ids
    // end wxGlade

    MetadataDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: MetadataDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MetadataDialog::attributes
    wxStyledTextCtrl* metadata_out;
    wxPanel* notebook_1_pane_1;
    wxStyledTextCtrl* sample;
    wxPanel* notebook_1_pane_2;
    wxNotebook* notebook_1;
    wxButton* button_save;
    wxButton* button_cancel;
    // end wxGlade
}; // wxGlade: end class


#endif // METADATADIALOG_H
