// -*- C++ -*-
//
// generated by wxGlade HG on Sat May 24 09:31:19 2014
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "MetadataDialog.h"

// begin wxGlade: ::extracode
// end wxGlade



MetadataDialog::MetadataDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: MetadataDialog::MetadataDialog
    notebook_1 = new wxNotebook(this, wxID_ANY);
    notebook_1_pane_2 = new wxPanel(notebook_1, wxID_ANY);
    notebook_1_pane_1 = new wxPanel(notebook_1, wxID_ANY);
    metadata_out = new wxStyledTextCtrl(notebook_1_pane_1, wxID_ANY);
    sample = new wxStyledTextCtrl(notebook_1_pane_2, wxID_ANY);
    button_save = new wxButton(this, wxID_OK, _("Save"));
    button_cancel = new wxButton(this, wxID_CANCEL, _("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MetadataDialog::set_properties()
{
    // begin wxGlade: MetadataDialog::set_properties
    SetTitle(_("metadata.xml"));
    SetSize(wxSize(400, 300));
    // end wxGlade
}


void MetadataDialog::do_layout()
{
    // begin wxGlade: MetadataDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    sizer_4->Add(metadata_out, 1, wxEXPAND, 0);
    notebook_1_pane_1->SetSizer(sizer_4);
    sizer_3->Add(sample, 1, wxEXPAND, 0);
    notebook_1_pane_2->SetSizer(sizer_3);
    notebook_1->AddPage(notebook_1_pane_1, _("metadata.xml"));
    notebook_1->AddPage(notebook_1_pane_2, _("sample"));
    sizer_1->Add(notebook_1, 1, wxALL|wxEXPAND, 8);
    sizer_2->Add(button_save, 0, wxLEFT, 80);
    sizer_2->Add(button_cancel, 0, wxLEFT, 60);
    sizer_1->Add(sizer_2, 0, wxALL|wxEXPAND, 8);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}


class MyApp: public wxApp {
public:
    bool OnInit();
protected:
    wxLocale m_locale;  // locale we'll be using
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    m_locale.Init();
#ifdef APP_LOCALE_DIR
    m_locale.AddCatalogLookupPathPrefix(wxT(APP_LOCALE_DIR));
#endif
    m_locale.AddCatalog(wxT(APP_CATALOG));

    wxInitAllImageHandlers();
    MetadataDialog* dialog_1 = new MetadataDialog(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(dialog_1);
    dialog_1->Show();
    return true;
}