#!/usr/bin/env python
# -*- coding: ANSI_X3.4-1968 -*-
#
# generated by wxGlade HG on Sat May 24 09:04:08 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.notebook = wx.Notebook(self, wx.ID_ANY)
        self.notebook_ext_apps = wx.Panel(self.notebook, wx.ID_ANY)
        self.text_ctrl_xterm = wx.TextCtrl(self.notebook_ext_apps, wx.ID_ANY, "")
        self.label_xterm_copy = wx.StaticText(self.notebook_ext_apps, wx.ID_ANY, _("Standard xterm is recommended\n(Konsole will open new sessions)"))
        self.sizer_xterm_staticbox = wx.StaticBox(self.notebook_ext_apps, wx.ID_ANY, _("xterm"))
        self.text_ctrl_editor = wx.TextCtrl(self.notebook_ext_apps, wx.ID_ANY, "")
        self.label_editor = wx.StaticText(self.notebook_ext_apps, wx.ID_ANY, _("External editor.\nIf using gvim use the -f option."))
        self.sizer_editor_staticbox = wx.StaticBox(self.notebook_ext_apps, wx.ID_ANY, _("Editor"))
        self.text_ctrl_browser = wx.TextCtrl(self.notebook_ext_apps, wx.ID_ANY, "")
        self.label_browser = wx.StaticText(self.notebook_ext_apps, wx.ID_ANY, _("Used for help system and\nchecking HOMEPAGE variable."))
        self.sizer_browser_staticbox = wx.StaticBox(self.notebook_ext_apps, wx.ID_ANY, _("Web browser"))
        self.text_ctrl_diff = wx.TextCtrl(self.notebook_ext_apps, wx.ID_ANY, "")
        self.label_diff = wx.StaticText(self.notebook_ext_apps, wx.ID_ANY, _("GUI diff program.\ngtkdiff, kompare etc."))
        self.sizer_diff_staticbox = wx.StaticBox(self.notebook_ext_apps, wx.ID_ANY, _("Graphical diff"))
        self.noteboo_pane_general = wx.Panel(self.notebook, wx.ID_ANY)
        self.checkbox_strip_header = wx.CheckBox(self.noteboo_pane_general, wx.ID_ANY, _("Auto-strip CVS header on save"))
        self.checkbox_clear_log_window = wx.CheckBox(self.noteboo_pane_general, wx.ID_ANY, _("Clear log window on new or loading ebuild"))
        self.checkbox_check_syntax = wx.CheckBox(self.noteboo_pane_general, wx.ID_ANY, _("Check syntax when saving"))
        self.checkbox_external_control = wx.CheckBox(self.noteboo_pane_general, wx.ID_ANY, _("Allow control from vim or gvim"))
        self.checkbox_logfile = wx.CheckBox(self.noteboo_pane_general, wx.ID_ANY, _("Log output to file"))
        self.text_ctrl_logfile = wx.TextCtrl(self.noteboo_pane_general, wx.ID_ANY, "")
        self.sizer_9_staticbox = wx.StaticBox(self.noteboo_pane_general, wx.ID_ANY, _("Logging"))
        self.noteboo_pane_editor = wx.Panel(self.notebook, wx.ID_ANY)
        self.button_font = wx.Button(self.noteboo_pane_editor, wx.ID_ANY, _("Font"))
        self.text_ctrl_font = wx.TextCtrl(self.noteboo_pane_editor, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.sizer_12_staticbox = wx.StaticBox(self.noteboo_pane_editor, wx.ID_ANY, _("Font"))
        self.checkbox_highlight = wx.CheckBox(self.noteboo_pane_editor, wx.ID_ANY, _("Sourcecode highlighting (color)"))
        self.checkbox_gentoo_highlighting = wx.CheckBox(self.noteboo_pane_editor, wx.ID_ANY, _("Highlight Gentoo keywords/functions/variables"))
        self.checkbox_whitespace = wx.CheckBox(self.noteboo_pane_editor, wx.ID_ANY, _("Show whitespace"))
        self.label_tabsize = wx.StaticText(self.noteboo_pane_editor, wx.ID_ANY, _("Spaces per tab char:"))
        self.text_ctrl_1 = wx.TextCtrl(self.noteboo_pane_editor, wx.ID_ANY, _("4"))
        self.noteboo_pane_dev = wx.Panel(self.notebook, wx.ID_ANY)
        self.label_cvs_root = wx.StaticText(self.noteboo_pane_dev, wx.ID_ANY, _("Enter directory for CVS root (e.g. ~/gentoo-x86)"))
        self.text_ctrl_cvs_root = wx.TextCtrl(self.noteboo_pane_dev, wx.ID_ANY, "")
        self.sizer_cvs_staticbox = wx.StaticBox(self.noteboo_pane_dev, wx.ID_ANY, _("CVS"))
        self.noteboo_pane_emerge = wx.Panel(self.notebook, wx.ID_ANY)
        self.label_USE = wx.StaticText(self.noteboo_pane_emerge, wx.ID_ANY, _("USE="))
        self.text_ctrl_USE = wx.TextCtrl(self.noteboo_pane_emerge, wx.ID_ANY, "")
        self.label_FEATURES = wx.StaticText(self.noteboo_pane_emerge, wx.ID_ANY, _("FEATURES="))
        self.text_ctrl_FEATURES = wx.TextCtrl(self.noteboo_pane_emerge, wx.ID_ANY, _("noauto"))
        self.button_save = wx.Button(self, wx.ID_OK, "")
        self.button_cancel = wx.Button(self, wx.ID_CANCEL, _("Cancel"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle(_("Preferences"))
        self.Hide()
        self.checkbox_external_control.Enable(False)
        self.button_save.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_cvs_staticbox.Lower()
        sizer_cvs = wx.StaticBoxSizer(self.sizer_cvs_staticbox, wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_12_staticbox.Lower()
        sizer_12 = wx.StaticBoxSizer(self.sizer_12_staticbox, wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_9_staticbox.Lower()
        sizer_9 = wx.StaticBoxSizer(self.sizer_9_staticbox, wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_ext_apps = wx.GridSizer(2, 2, 10, 10)
        self.sizer_diff_staticbox.Lower()
        sizer_diff = wx.StaticBoxSizer(self.sizer_diff_staticbox, wx.VERTICAL)
        self.sizer_browser_staticbox.Lower()
        sizer_browser = wx.StaticBoxSizer(self.sizer_browser_staticbox, wx.VERTICAL)
        self.sizer_editor_staticbox.Lower()
        sizer_editor = wx.StaticBoxSizer(self.sizer_editor_staticbox, wx.VERTICAL)
        self.sizer_xterm_staticbox.Lower()
        sizer_xterm = wx.StaticBoxSizer(self.sizer_xterm_staticbox, wx.VERTICAL)
        sizer_xterm.Add(self.text_ctrl_xterm, 0, wx.ALL | wx.EXPAND, 4)
        sizer_xterm.Add(self.label_xterm_copy, 0, 0, 0)
        grid_sizer_ext_apps.Add(sizer_xterm, 0, wx.ALL | wx.EXPAND, 4)
        sizer_editor.Add(self.text_ctrl_editor, 0, wx.ALL | wx.EXPAND, 4)
        sizer_editor.Add(self.label_editor, 0, 0, 12)
        grid_sizer_ext_apps.Add(sizer_editor, 0, wx.ALL | wx.EXPAND, 4)
        sizer_browser.Add(self.text_ctrl_browser, 0, wx.ALL | wx.EXPAND, 4)
        sizer_browser.Add(self.label_browser, 0, 0, 0)
        grid_sizer_ext_apps.Add(sizer_browser, 0, wx.ALL | wx.EXPAND, 4)
        sizer_diff.Add(self.text_ctrl_diff, 0, wx.ALL | wx.EXPAND, 4)
        sizer_diff.Add(self.label_diff, 0, 0, 0)
        grid_sizer_ext_apps.Add(sizer_diff, 1, wx.ALL | wx.EXPAND, 4)
        self.notebook_ext_apps.SetSizer(grid_sizer_ext_apps)
        sizer_8.Add(self.checkbox_strip_header, 0, wx.ALL, 8)
        sizer_8.Add(self.checkbox_clear_log_window, 0, wx.ALL, 8)
        sizer_8.Add(self.checkbox_check_syntax, 0, wx.ALL, 8)
        sizer_8.Add(self.checkbox_external_control, 0, wx.ALL, 8)
        sizer_10.Add(self.checkbox_logfile, 0, wx.ALL, 8)
        sizer_10.Add(self.text_ctrl_logfile, 1, wx.ALL, 8)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_9, 0, wx.EXPAND, 0)
        self.noteboo_pane_general.SetSizer(sizer_8)
        sizer_12.Add(self.button_font, 0, wx.ALL, 8)
        sizer_12.Add(self.text_ctrl_font, 1, wx.ALL, 8)
        sizer_11.Add(sizer_12, 0, wx.ALL | wx.EXPAND, 12)
        sizer_11.Add(self.checkbox_highlight, 0, wx.ALL | wx.EXPAND, 12)
        sizer_11.Add(self.checkbox_gentoo_highlighting, 0, wx.ALL | wx.EXPAND, 12)
        sizer_11.Add(self.checkbox_whitespace, 0, wx.ALL | wx.EXPAND, 12)
        sizer_3.Add(self.label_tabsize, 0, wx.LEFT | wx.RIGHT, 12)
        sizer_3.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_11.Add(sizer_3, 1, wx.EXPAND, 0)
        self.noteboo_pane_editor.SetSizer(sizer_11)
        sizer_cvs.Add(self.label_cvs_root, 0, wx.LEFT | wx.TOP | wx.EXPAND, 12)
        sizer_cvs.Add(self.text_ctrl_cvs_root, 0, wx.ALL | wx.EXPAND, 12)
        sizer_13.Add(sizer_cvs, 0, wx.ALL | wx.EXPAND, 20)
        self.noteboo_pane_dev.SetSizer(sizer_13)
        sizer_17.Add(self.label_USE, 0, wx.ALL, 12)
        sizer_17.Add(self.text_ctrl_USE, 1, wx.ALL, 12)
        sizer_16.Add(sizer_17, 0, wx.EXPAND, 0)
        sizer_18.Add(self.label_FEATURES, 0, wx.ALL, 12)
        sizer_18.Add(self.text_ctrl_FEATURES, 1, wx.ALL, 12)
        sizer_16.Add(sizer_18, 0, wx.EXPAND, 0)
        self.noteboo_pane_emerge.SetSizer(sizer_16)
        self.notebook.AddPage(self.notebook_ext_apps, _("External apps"))
        self.notebook.AddPage(self.noteboo_pane_general, _("General"))
        self.notebook.AddPage(self.noteboo_pane_editor, _("Editor"))
        self.notebook.AddPage(self.noteboo_pane_dev, _("Gentoo Developer"))
        self.notebook.AddPage(self.noteboo_pane_emerge, _("Emerge"))
        sizer_1.Add(self.notebook, 1, wx.ALL | wx.EXPAND, 4)
        sizer_2.Add(self.button_save, 0, wx.LEFT, 20)
        sizer_2.Add(self.button_cancel, 0, wx.LEFT, 20)
        sizer_1.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 12)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyDialog
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        PrefsDialog = MyDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(PrefsDialog)
        PrefsDialog.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()