#!/usr/bin/env python
# generated by wxGlade 0.3.3 on Fri Aug  6 12:07:29 2004

import os

import wx
import wx.html


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.window_1 = wx.SplitterWindow(self, -1)
        self.window_1_pane_2 = wx.Panel(self.window_1, -1, style=wx.NO_BORDER|wx.TAB_TRAVERSAL)
        self.window_2 = wx.SplitterWindow(self.window_1_pane_2, -1)
        self.window_2_pane_2 = wx.Panel(self.window_2, -1, style=wx.NO_BORDER|wx.TAB_TRAVERSAL)
        self.window_2_pane_1 = wx.Panel(self.window_2, -1, style=wx.NO_BORDER|wx.TAB_TRAVERSAL)
        self.window_1_pane_1 = wx.Panel(self.window_1, -1, style=wx.NO_BORDER|wx.TAB_TRAVERSAL)
        self.list_box_1 = wx.ListBox(self.window_1_pane_1, -1, choices=[])
        self.html_window = wx.html.HtmlWindow(self.window_2_pane_1, -1)
        self.text_ctrl_function_contents = wx.TextCtrl(self.window_2_pane_2, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Private Portage Functions")
        self.SetSize((700, 500))
        self.list_box_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.window_2_pane_2, -1, "Function Contents:"), wx.HORIZONTAL)
        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.window_2_pane_1, -1, "Help:"), wx.HORIZONTAL)
        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, -1, "Portage Functions:"), wx.HORIZONTAL)
        sizer_2.Add(self.list_box_1, 1, wx.ALL|wx.EXPAND, 4)
        self.window_1_pane_1.SetAutoLayout(1)
        self.window_1_pane_1.SetSizer(sizer_2)
        sizer_2.Fit(self.window_1_pane_1)
        sizer_2.SetSizeHints(self.window_1_pane_1)
        sizer_4.Add(self.html_window, 1, wx.EXPAND, 0)
        self.window_2_pane_1.SetAutoLayout(1)
        self.window_2_pane_1.SetSizer(sizer_4)
        sizer_4.Fit(self.window_2_pane_1)
        sizer_4.SetSizeHints(self.window_2_pane_1)
        sizer_5.Add(self.text_ctrl_function_contents, 1, wx.ALL|wx.EXPAND, 6)
        self.window_2_pane_2.SetAutoLayout(1)
        self.window_2_pane_2.SetSizer(sizer_5)
        sizer_5.Fit(self.window_2_pane_2)
        sizer_5.SetSizeHints(self.window_2_pane_2)
        self.window_2.SplitHorizontally(self.window_2_pane_1, self.window_2_pane_2, 239)
        sizer_3.Add(self.window_2, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetAutoLayout(1)
        self.window_1_pane_2.SetSizer(sizer_3)
        sizer_3.Fit(self.window_1_pane_2)
        sizer_3.SetSizeHints(self.window_1_pane_2)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2, 173)
        sizer_1.Add(self.window_1, 1, wx.ALL|wx.EXPAND, 6)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

        wx.EVT_LISTBOX(self, self.list_box_1.GetId(), self.OnListbox)
        t = 'dobin doconfd dodir dodoc doenvd doexe dohard dohtml doinfo doinitd doins dojar dolib dolib.a dolib.so doman domo donewins dopython dosbin dosed dosym ebuild.sh emake fowners fperms newbin newconfd newdoc newenvd newexe newinitd newins newlib.a newlib.so newman newsbin pmake prepall prepalldocs prepalldocs.new prepallinfo prepallman prepallstrip prepinfo preplib preplib.so prepman prepstrip quickpkg xpak'

        funcs = t.split(" ")
        for f in funcs:
            self.list_box_1.Append(f)

    def OnListbox(self, evt):
        """Show help and function contents on click"""
        func = self.list_box_1.GetStringSelection()
        d = "/usr/lib/portage/bin"
        file = "%s/%s" % (d, func)
        if os.path.exists(file):
            msg = open(file, "r").read()
            self.text_ctrl_function_contents.SetValue(msg)
        else:
            self.text_ctrl_function_contents.SetValue('')
        d = "/usr/share/abeni/priv_funcs"
        file = "%s/%s" % (d, func)
        if os.path.exists(file):
            msg = open(file, "r").read()
            self.html_window.SetPage(msg)
            #self.text_ctrl_help.SetValue(msg)
        else:
            self.html_window.SetPage('<br>No help available on this function.<br><br>Feel free to submit some.<br>Email pythonhead@gentoo.org')
            #self.text_ctrl_help.SetValue('\nNo help available on this function.\n\nFeel free to submit some.\nEmail pythonhead@gentoo.org')
 
# end of class MyDialog


